export default defineActionConstants([
  'OPEN_APP',
  'FETCH_CURRENT_USER',
  'FETCH_CURRENT_USER_SUCCESS',
  'FETCH_CURRENT_USER_FAILURE',
  'SET_CURRENT_USER',
  'SIGN_OUT',

  'SET_AUTH_TOKEN',
  'AUTH_TOKEN_REQUEST',
  'AUTH_TOKEN_SUCCESS',
  'AUTH_TOKEN_FAILURE',

  'FETCH_PROJECTS_REQUEST',
  'FETCH_PROJECTS_SUCCESS',
  'FETCH_PROJECTS_FAILURE',

  'FETCH_BUGS_REQUEST',
  'FETCH_BUGS_SUCCESS',
  'FETCH_BUGS_FAILURE',

  'FETCH_COMPONENTS_REQUEST',
  'FETCH_COMPONENTS_SUCCESS',
  'FETCH_COMPONENTS_FAILURE',

  'FETCH_VERSIONS_REQUEST',
  'FETCH_VERSIONS_SUCCESS',
  'FETCH_VERSIONS_FAILURE',

  'FETCH_BUG_REQUEST',
  'FETCH_BUG_SUCCESS',
  'FETCH_BUG_FAILURE',

  'FETCH_ORGS_REQUEST',
  'FETCH_ORGS_SUCCESS',
  'FETCH_ORGS_FAILURE',

  'BUG_REPORT_SET_TITLE',
  'BUG_REPORT_SET_DESCRIPTION',
  'BUG_REPORT_SET_EXPECTED_RESULTS',
  'BUG_REPORT_SET_PRIORITY',
  'BUG_REPORT_SET_SEVERITY',
  'BUG_REPORT_SET_PROJECT',
  'BUG_REPORT_SET_VERSION',
  'BUG_REPORT_SET_TYPE',
  'BUG_REPORT_SET_STATUS',
  'BUG_REPORT_SET_COMPONENT',
  'BUG_REPORT_SET_STEPS',
  'BUG_REPORT_ADD_FILE',
  'BUG_REPORT_REMOVE_FILE',
  'BUG_REPORT_RESET',

  'CREATE_BUG_REQUEST',
  'CREATE_BUG_PROGRESS',
  'CREATE_BUG_FAILURE',
  'CREATE_BUG_SUCCESS',

  'UPDATE_BUG_REQUEST',
  'UPDATE_BUG_FAILURE',
  'UPDATE_BUG_SUCCESS',

  'NETWORK_OPERATION_START',
  'NETWORK_OPERATION_END',
  'RESET_ERROR_MESSAGE',
]);

function defineActionConstants(names) {
  return names.reduce((result, name) => {
    result[name] = name;
    return result;
  }, {});
}
